# syntax=docker/dockerfile:1

FROM ubuntu-chrome-nodejs
# ENV NODE_ENV=production

WORKDIR /app

COPY ["package.json", "yarn.lock", "./"]

RUN npm install --global yarn

# RUN yarn install --production
RUN yarn install

COPY . .

CMD [ "yarn", "test" ]
