version: "3.9"

services:
  web:
    build: .
    image: test-vue:latest
    networks:
      e2etest:
        aliases:
          - vue
    ports:
      - 8081:8080
  selenium:
    build:
      context: .
      dockerfile: Dockerfile.selenium
    image: selenium:latest
    #network_mode: "host"
    networks:
      - e2etest
    command: bash -c "sleep 10 && yarn test"
    environment:
      - TESTVUE_URL=http://web:8080/
      #- TESTVUE_URL=http://vue:8080/
      #- TESTVUE_URL=http://seleniumtest_web_1:8080/
      #- TESTVUE_URL=http://192.168.32.2:8080/
    #depends_on:
    #  - web

networks:
  e2etest:
